name: Request maintenance
description: Submit a request for maintenance of the project's dependencies, development tools, or source code.
labels:
    - maintenance
body:
    - type: markdown
      attributes:
          value: |
              * Check to make sure someone hasn't already opened a similar maintenance request [issue](https://github.com/zachwatkins/remarklet/issues).

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: This project has a Code of Conduct that all participants are expected to understand and follow.
          options:
              - label: I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/zachwatkins/remarklet/blob/main/CODE_OF_CONDUCT.md)
                required: true

    - type: textarea
      attributes:
          label: What part of the project is involved?
          description: Include links, screenshots, what browser you're using, etc.
      validations:
          required: true

    - type: textarea
      attributes:
          label: What changes are you suggesting?
          description: |
              - Give as much detail as you can to help us understand the change you want to see.
              - Why should the project be changed? What use cases does it support?
              - What is the expected outcome?
      validations:
          required: true

    - type: checkboxes
      attributes:
          label: Pull Request
          description: When submitting a pull request, please be sure to complete each of the following.
          options:
              - label: MUST reference this issue, e.g. via `closes [this issue number]`.
                required: true
              - label: MUST pass the automated CI checks.
                required: true
