name: Triage new issues

on:
  issues:
    types: [opened, reopened, edited]
  workflow_call:

jobs:
  triage_issues:
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/issue-labeler.yml
          include-title: 1
          enable-versioned-regex: 0
